version: '3'
services:
  app:
    image: ggarruch/rotten-potatoes:v1
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mongo
    ports:
      - 5000:5000
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongo
      MONGODB_PORT: "27017"
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopwd@mongo:27017/


